### ISSUE TITLE
Chapter duplicated when switching Scene Collection.

### ISSUE THREAD

**Issue by kuswanto** [StreamUPTips/obs-chapter-marker-manager#2]
My setup require me to switch scene collections between recording depend on when I record on PC or console games. When I change scene collection, list of chapter Markers is duplicated.

Before switching
![image](https://github.com/user-attachments/assets/3fe66e04-ea05-4137-9a43-64327e548d1d)

After Switching to another scene collection.
![image](https://github.com/user-attachments/assets/7f1d42c0-988a-486b-b1b8-6b25f7402878)

This issue also duplicate the shortcuts list in Settings
![image](https://github.com/user-attachments/assets/3fb2e2d4-524e-4cec-bb12-51dc244fd957)

**Comment by andilippi** [comment]
Thank you for this report. This will be fixed in the next patch launching tomorrow!
